name: gamma-api-users

services:
  db-users:
    container_name: gamma-db-users
    image: mariadb
    restart: always
    env_file: ".env"
    networks:
      - gamma-network

networks:
  gamma-network:
    external: true